name: Build and push the devcontainer

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-devcontainer:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/viginum-fr/d3lta
          cacheFrom: ghcr.io/viginum-fr/d3lta
