name: Run tests

on: push

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --with dev 

    - name: Run tests
      run: poetry run pytest
