name: Test building the devcontainer

on:  # test on any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build-devcontainer:
    name: Test building the dev container
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/viginum-fr/d3lta
          cacheFrom: ghcr.io/viginum-fr/d3lta
          push: never
